import {isAdmin} from '/imports/common';
import {accessControlSchema} from '/imports/schemas/misc';
import {Meteor} from 'meteor/meteor';

AMx = new Mongo.Collection("AccessControl");

Meteor.startup(function () {
    AMx.attachSchema(accessControlSchema);
});

if(Meteor.isServer) {
    Meteor.methods({
        /**
         * @summary Check whether the logged in user is allowed to perform an operation. The operation could be creating,
         * viewing, deleting or responding to a feed item of a specific type. If specified permission is not defined, an
         *  error is thrown.
         * @param {String} itemType The item for which the permission is being requested.
         * @param {String} permission The type of permission being requested for the item: could be create, view, edit or delete.
         * @return True if the logged in user is allowed to perform the specified operation. Otherwise false.
         * @throws error if the input parameters do not have the required type.
         * @throws error if the specified permission is not defined.
         */
        checkRights: function (itemType, permission) {
            check(itemType, String);
            check(permission, String);
            check(Meteor.user(), Object);

            var doc = AMx.findOne(
                {'_id': Meteor.user().profile.type},
                {fields: {'items': {$elemMatch: {'_id': itemType}}}}
            );

            if (!doc.items) {
                throw new Meteor.Error(404, 'No such permission defined');
            }
            
            return doc.items[0].permissions[permission];
        },
        /**
         * @summary Create or update a new set of permissions for a user type. A document that contains both the user type
         *  and an access matrix for all operations should be passed to this function. The matrix should comply to the
         *  corresponding database scheme. It defines whether a user of a specific type is allowed to perform a operation.
         * @param{Object} newAccess A document object that contains all attributes required in the 'accessControlSchema' .
         * @return{String} The id of the inserted document of the permissions. It is automatically generated by MongoDB.
         * @throws error if 'newAccess' does not conform to the database scheme.
         * @throws error if the logged in user is not allowed to set permissions.
         */
        setPermissions: function (newAccess) {
            check(Meteor.userId(), Match.Where(isAdmin));
            check(newAccess, accessControlSchema);
            return AMx.insert(newAccess);
        }
    });
}